#!/usr/bin/env python3
"""Pre-registers word family entries as drafts in the DB.

These are words identified during Word Workshop sessions as likely matches
for new mechanics. They are marked status='draft' so ralph-loop knows they
need refinement. When ralph-loop re-classifies a draft word, it overwrites
the entry with status=NULL (refined).

Run after seed_db.py to layer draft words on top of seeds.
"""

import json
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(__file__)
BATCH_INSERT = os.path.join(SCRIPT_DIR, "batch_insert.py")

# Pre-registered word families from Word Workshop sessions.
# Each family groups words that share a mechanic (action/tag).
# These are preliminary classifications — ralph-loop should refine them.

FAMILIES = [
    # --- Purify family (cleanse negative statuses) ---
    {"word": "cleanse",  "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["HOLY", "RESTORATION", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 2}]},
    {"word": "cure",     "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 1}]},
    {"word": "remedy",   "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 1}, {"action": "Heal", "value": 2}]},
    {"word": "antidote", "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 2}]},
    {"word": "rinse",    "target": "AllAlliesAndSelf", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CLEANSING", "NATURE"],
     "actions": [{"action": "Purify", "value": 1}]},
    {"word": "wash",     "target": "AllAlliesAndSelf", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CLEANSING", "NATURE"],
     "actions": [{"action": "Purify", "value": 1}, {"action": "Water", "value": 1}]},
    {"word": "baptize",  "target": "AllAlliesAndSelf", "cost": 3, "range": 0, "area": "Single",
     "tags": ["HOLY", "RESTORATION", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 3}, {"action": "Heal", "value": 2}]},

    # --- Awaken family (remove CC + stat buff) ---
    {"word": "rouse",    "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT"],
     "actions": [{"action": "Awaken", "value": 1}]},
    {"word": "revive",   "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["HOLY", "RESTORATION", "SUPPORT"],
     "actions": [{"action": "Awaken", "value": 1}, {"action": "Heal", "value": 2}]},
    {"word": "stir",     "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT"],
     "actions": [{"action": "Awaken", "value": 1}]},

    # --- Siphon family (steal stats from enemies) ---
    {"word": "drain",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "leech",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "extract",  "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "STEALTH"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "devour",   "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "OFFENSIVE"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Damage", "value": 2}]},
    {"word": "parasitic","target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "NATURE"],
     "actions": [{"action": "Siphon", "value": 1}]},

    # --- Deceive family (Fear + Concussion combo) ---
    {"word": "trick",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "SHADOW"],
     "actions": [{"action": "Deceive", "value": 1}]},
    {"word": "mislead",  "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "SHADOW", "DEBUFF"],
     "actions": [{"action": "Deceive", "value": 2}]},
    {"word": "confuse",  "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "DEBUFF"],
     "actions": [{"action": "Deceive", "value": 1}]},
    {"word": "bewilder", "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "DEBUFF"],
     "actions": [{"action": "Deceive", "value": 2}]},
    {"word": "bluff",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "SOCIAL"],
     "actions": [{"action": "Deceive", "value": 1}]},

    # --- Recuperate family (heal + cleanse one negative status) ---
    {"word": "recover",   "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT"],
     "actions": [{"action": "Recuperate", "value": 2}]},
    {"word": "unwind",    "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "RELAX"],
     "actions": [{"action": "Recuperate", "value": 1}]},
    {"word": "convalesce","target": "Self",             "cost": 2, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT"],
     "actions": [{"action": "Recuperate", "value": 3}]},
    {"word": "nurse",     "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT"],
     "actions": [{"action": "Recuperate", "value": 2}]},

    # --- Comfort family (apply Energetic to ally) ---
    {"word": "encourage", "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}]},
    {"word": "reassure",  "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}]},
    {"word": "inspire",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}, {"action": "BuffStrength", "value": 1}]},
    {"word": "uplift",    "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "HOLY"],
     "actions": [{"action": "Comfort", "value": 1}]},
    {"word": "embolden",  "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}, {"action": "BuffMagicPower", "value": 1}]},

    # --- Overcharge family (MagicPower buff + Energetic) ---
    {"word": "surge",      "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SPELL"],
     "actions": [{"action": "Overcharge", "value": 2}]},
    {"word": "jolt",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "OFFENSIVE"],
     "actions": [{"action": "Overcharge", "value": 1}]},
    {"word": "electrify",  "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SPELL"],
     "actions": [{"action": "Overcharge", "value": 2}]},
    {"word": "galvanize",  "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SUPPORT"],
     "actions": [{"action": "Overcharge", "value": 2}]},
    {"word": "supercharge","target": "Self", "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SPELL"],
     "actions": [{"action": "Overcharge", "value": 3}, {"action": "Shock", "value": 2}]},

    # --- LIGHTNING tag family (words that should get LIGHTNING tag) ---
    {"word": "lightning",  "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "SPELL", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 3}]},
    {"word": "bolt",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 2}]},
    {"word": "voltage",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 2}]},
    {"word": "zap",        "target": "SingleEnemy", "cost": 0, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 1}]},
    {"word": "thunder",    "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "SPELL", "LIGHTNING", "WEATHER"],
     "actions": [{"action": "Shock", "value": 3}, {"action": "Fear", "value": 1}]},

    # --- BOTANICAL tag family (plants/flowers) ---
    {"word": "rose",       "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 2}]},
    {"word": "vine",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "OFFENSIVE"],
     "actions": [{"action": "Slow", "value": 2}]},
    {"word": "sprout",     "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Grow", "value": 1}]},
    {"word": "petal",      "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "moss",       "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "RESTORATION"],
     "actions": [{"action": "Shield", "value": 1}]},
    {"word": "fern",       "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "orchid",     "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "RESTORATION"],
     "actions": [{"action": "Heal", "value": 2}, {"action": "Grow", "value": 1}]},
    {"word": "lily",       "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "tulip",      "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "blossom",    "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "RESTORATION"],
     "actions": [{"action": "Heal", "value": 2}]},

    # --- DRAIN tag family (parasitic/draining) ---
    {"word": "sap",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "deplete",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 2}]},
    {"word": "consume",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN", "OFFENSIVE"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Damage", "value": 2}]},
    {"word": "parasite",   "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "NATURE", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "wither",     "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN", "NATURE"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Slow", "value": 1}]},
    {"word": "vampire",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Heal", "value": 2}]},

    # --- WEATHER tag family ---
    {"word": "storm",      "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 2}, {"action": "Water", "value": 2}]},
    {"word": "hail",       "target": "AllEnemies",  "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Freeze", "value": 1}]},
    {"word": "blizzard",   "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER"],
     "actions": [{"action": "Freeze", "value": 2}, {"action": "MagicDamage", "value": 2}]},
    {"word": "tornado",    "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER", "NATURE"],
     "actions": [{"action": "Damage", "value": 3}, {"action": "Scramble", "value": 1}]},
    {"word": "cyclone",    "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER", "NATURE"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Push", "value": 2}]},

    # --- Cannonade family (multi-hit random targeting) ---
    {"word": "volley",      "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 2}]},
    {"word": "bombardment", "target": "AllEnemies", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 4}]},
    {"word": "salvo",       "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 3}]},
    {"word": "broadside",   "target": "AllEnemies", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 4}]},
    {"word": "fusillade",   "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE"],
     "actions": [{"action": "Cannonade", "value": 3}]},

    # --- Plunder family (damage + stat steal) ---
    {"word": "pillage",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW", "MELEE"],
     "actions": [{"action": "Plunder", "value": 2}]},
    {"word": "loot",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW"],
     "actions": [{"action": "Plunder", "value": 1}]},
    {"word": "raid",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE"],
     "actions": [{"action": "Plunder", "value": 2}]},
    {"word": "ransack",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW", "MELEE"],
     "actions": [{"action": "Plunder", "value": 3}]},
    {"word": "maraud",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW"],
     "actions": [{"action": "Plunder", "value": 1}]},

    # --- UNDEAD tag family ---
    {"word": "specter",     "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Fear", "value": 2}]},
    {"word": "ghoul",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Poison", "value": 1}]},
    {"word": "revenant",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 3}]},
    {"word": "banshee",     "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Screech", "value": 1}]},

    # --- NAVAL tag family ---
    {"word": "anchor",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NAVAL", "PHYSICAL", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Slow", "value": 1}]},
    {"word": "sail",        "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NAVAL", "SUPPORT"],
     "actions": [{"action": "Energize", "value": 1}]},
    {"word": "hull",        "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["NAVAL", "DEFENSIVE"],
     "actions": [{"action": "Shield", "value": 2}]},
    {"word": "cannon",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NAVAL", "OFFENSIVE"],
     "actions": [{"action": "Cannonade", "value": 2}]},

    # --- Attune family (save letters for power amplification) ---
    {"word": "harmonize",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "resonate",    "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "synchronize", "target": "Self", "cost": 3, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "calibrate",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "align",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "tune",        "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "chord",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "frequency",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},

    # --- Ignite family (fire damage + burn) ---
    {"word": "kindle",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "inflame",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 2}]},
    {"word": "scald",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "sear",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "char",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "singe",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "cauterize",   "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 2}]},
    {"word": "incinerate",  "target": "SingleEnemy", "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 3}]},

    # --- Combust family (detonate burning) ---
    {"word": "detonate",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "explode",     "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "erupt",       "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "rupture",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "burst",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 1}]},
    {"word": "implode",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},

    # --- FIRE tag family (fire-themed words needing FIRE tag) ---
    {"word": "ash",         "target": "SingleEnemy", "cost": 0, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "FIRE"],
     "actions": [{"action": "Burn", "value": 1}]},
    {"word": "cinder",      "target": "SingleEnemy", "cost": 0, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "FIRE"],
     "actions": [{"action": "Burn", "value": 1}]},
    {"word": "pyre",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Damage", "value": 1}]},
    {"word": "magma",       "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Melt", "value": 1}]},
    {"word": "lava",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Melt", "value": 1}]},
    {"word": "volcano",     "target": "AllEnemies",  "cost": 4, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE", "NATURE"],
     "actions": [{"action": "Ignite", "value": 3}, {"action": "Damage", "value": 3}]},
]


def main():
    proc = subprocess.run(
        [sys.executable, BATCH_INSERT, "--draft"],
        input=json.dumps(FAMILIES),
        capture_output=True,
        text=True,
    )
    if proc.stderr:
        print(proc.stderr, end="", file=sys.stderr)
    if proc.returncode != 0:
        print(f"preregister_families failed (exit {proc.returncode})", file=sys.stderr)
        sys.exit(proc.returncode)
    print(f"Pre-registered {len(FAMILIES)} draft words from word families.", file=sys.stderr)


if __name__ == "__main__":
    main()
