#!/usr/bin/env python3
"""Pre-registers word family entries as drafts in the DB.

These are words identified during Word Workshop sessions as likely matches
for new mechanics. They are marked status='draft' so ralph-loop knows they
need refinement. When ralph-loop re-classifies a draft word, it overwrites
the entry with status=NULL (refined).

Run after seed_db.py to layer draft words on top of seeds.
"""

import json
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(__file__)
BATCH_INSERT = os.path.join(SCRIPT_DIR, "batch_insert.py")

# Pre-registered word families from Word Workshop sessions.
# Each family groups words that share a mechanic (action/tag).
# These are preliminary classifications — ralph-loop should refine them.

FAMILIES = [
    # --- Purify family (cleanse negative statuses) ---
    {"word": "cleanse",  "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["HOLY", "RESTORATION", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 2}]},
    {"word": "cure",     "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 1}]},
    {"word": "remedy",   "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 1}, {"action": "Heal", "value": 2}]},
    {"word": "antidote", "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 2}]},
    {"word": "rinse",    "target": "AllAlliesAndSelf", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CLEANSING", "NATURE"],
     "actions": [{"action": "Purify", "value": 1}]},
    {"word": "wash",     "target": "AllAlliesAndSelf", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CLEANSING", "NATURE"],
     "actions": [{"action": "Purify", "value": 1}, {"action": "Water", "value": 1}]},
    {"word": "baptize",  "target": "AllAlliesAndSelf", "cost": 3, "range": 0, "area": "Single",
     "tags": ["HOLY", "RESTORATION", "CLEANSING"],
     "actions": [{"action": "Purify", "value": 3}, {"action": "Heal", "value": 2}]},

    # --- Awaken family (remove CC + stat buff) ---
    {"word": "rouse",    "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT"],
     "actions": [{"action": "Awaken", "value": 1}]},
    {"word": "revive",   "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["HOLY", "RESTORATION", "SUPPORT"],
     "actions": [{"action": "Awaken", "value": 1}, {"action": "Heal", "value": 2}]},
    {"word": "stir",     "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT"],
     "actions": [{"action": "Awaken", "value": 1}]},

    # --- Siphon family (steal stats from enemies) ---
    {"word": "drain",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "leech",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "extract",  "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "STEALTH"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "devour",   "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "OFFENSIVE"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Damage", "value": 2}]},
    {"word": "parasitic","target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "NATURE"],
     "actions": [{"action": "Siphon", "value": 1}]},

    # --- Deceive family (Fear + Concussion combo) ---
    {"word": "trick",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "SHADOW"],
     "actions": [{"action": "Deceive", "value": 1}]},
    {"word": "mislead",  "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "SHADOW", "DEBUFF"],
     "actions": [{"action": "Deceive", "value": 2}]},
    {"word": "confuse",  "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "DEBUFF"],
     "actions": [{"action": "Deceive", "value": 1}]},
    {"word": "bewilder", "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "DEBUFF"],
     "actions": [{"action": "Deceive", "value": 2}]},
    {"word": "bluff",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["PSYCHIC", "SOCIAL"],
     "actions": [{"action": "Deceive", "value": 1}]},

    # --- Recuperate family (heal + cleanse one negative status) ---
    {"word": "recover",   "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT"],
     "actions": [{"action": "Recuperate", "value": 2}]},
    {"word": "unwind",    "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "RELAX"],
     "actions": [{"action": "Recuperate", "value": 1}]},
    {"word": "convalesce","target": "Self",             "cost": 2, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT"],
     "actions": [{"action": "Recuperate", "value": 3}]},
    {"word": "nurse",     "target": "Self",             "cost": 1, "range": 0, "area": "Single",
     "tags": ["RESTORATION", "SUPPORT"],
     "actions": [{"action": "Recuperate", "value": 2}]},

    # --- Comfort family (apply Energetic to ally) ---
    {"word": "encourage", "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}]},
    {"word": "reassure",  "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}]},
    {"word": "inspire",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}, {"action": "BuffStrength", "value": 1}]},
    {"word": "uplift",    "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "HOLY"],
     "actions": [{"action": "Comfort", "value": 1}]},
    {"word": "embolden",  "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [{"action": "Comfort", "value": 1}, {"action": "BuffMagicPower", "value": 1}]},

    # --- Overcharge family (MagicPower buff + Energetic) ---
    {"word": "surge",      "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SPELL"],
     "actions": [{"action": "Overcharge", "value": 2}]},
    {"word": "jolt",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "OFFENSIVE"],
     "actions": [{"action": "Overcharge", "value": 1}]},
    {"word": "electrify",  "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SPELL"],
     "actions": [{"action": "Overcharge", "value": 2}]},
    {"word": "galvanize",  "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SUPPORT"],
     "actions": [{"action": "Overcharge", "value": 2}]},
    {"word": "supercharge","target": "Self", "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "LIGHTNING", "SPELL"],
     "actions": [{"action": "Overcharge", "value": 3}, {"action": "Shock", "value": 2}]},

    # --- LIGHTNING tag family (words that should get LIGHTNING tag) ---
    {"word": "lightning",  "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "SPELL", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 3}]},
    {"word": "bolt",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 2}]},
    {"word": "voltage",    "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 2}]},
    {"word": "zap",        "target": "SingleEnemy", "cost": 0, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 1}]},
    {"word": "thunder",    "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "SPELL", "LIGHTNING", "WEATHER"],
     "actions": [{"action": "Shock", "value": 3}, {"action": "Fear", "value": 1}]},

    # --- BOTANICAL tag family (plants/flowers) ---
    {"word": "rose",       "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 2}]},
    {"word": "vine",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "OFFENSIVE"],
     "actions": [{"action": "Slow", "value": 2}]},
    {"word": "sprout",     "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Grow", "value": 1}]},
    {"word": "petal",      "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "moss",       "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "RESTORATION"],
     "actions": [{"action": "Shield", "value": 1}]},
    {"word": "fern",       "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "orchid",     "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "RESTORATION"],
     "actions": [{"action": "Heal", "value": 2}, {"action": "Grow", "value": 1}]},
    {"word": "lily",       "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "tulip",      "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL"],
     "actions": [{"action": "Heal", "value": 1}]},
    {"word": "blossom",    "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["NATURE", "BOTANICAL", "RESTORATION"],
     "actions": [{"action": "Heal", "value": 2}]},

    # --- DRAIN tag family (parasitic/draining) ---
    {"word": "sap",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "deplete",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 2}]},
    {"word": "consume",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN", "OFFENSIVE"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Damage", "value": 2}]},
    {"word": "parasite",   "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "NATURE", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 1}]},
    {"word": "wither",     "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN", "NATURE"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Slow", "value": 1}]},
    {"word": "vampire",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEBUFF", "SHADOW", "DRAIN"],
     "actions": [{"action": "Siphon", "value": 1}, {"action": "Heal", "value": 2}]},

    # --- WEATHER tag family ---
    {"word": "storm",      "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 2}, {"action": "Water", "value": 2}]},
    {"word": "hail",       "target": "AllEnemies",  "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Freeze", "value": 1}]},
    {"word": "blizzard",   "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER"],
     "actions": [{"action": "Freeze", "value": 2}, {"action": "MagicDamage", "value": 2}]},
    {"word": "tornado",    "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER", "NATURE"],
     "actions": [{"action": "Damage", "value": 3}, {"action": "Scramble", "value": 1}]},
    {"word": "cyclone",    "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "WEATHER", "NATURE"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Scramble", "value": 2}]},

    # --- Cannonade family (multi-hit random targeting) ---
    {"word": "volley",      "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 2}]},
    {"word": "bombardment", "target": "AllEnemies", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 4}]},
    {"word": "salvo",       "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 3}]},
    {"word": "broadside",   "target": "AllEnemies", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "NAVAL"],
     "actions": [{"action": "Cannonade", "value": 4}]},
    {"word": "fusillade",   "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE"],
     "actions": [{"action": "Cannonade", "value": 3}]},

    # --- Plunder family (damage + stat steal) ---
    {"word": "pillage",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW", "MELEE"],
     "actions": [{"action": "Plunder", "value": 2}]},
    {"word": "loot",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW"],
     "actions": [{"action": "Plunder", "value": 1}]},
    {"word": "raid",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE"],
     "actions": [{"action": "Plunder", "value": 2}]},
    {"word": "ransack",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW", "MELEE"],
     "actions": [{"action": "Plunder", "value": 3}]},
    {"word": "maraud",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW"],
     "actions": [{"action": "Plunder", "value": 1}]},

    # --- UNDEAD tag family ---
    {"word": "specter",     "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Fear", "value": 2}]},
    {"word": "ghoul",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Poison", "value": 1}]},
    {"word": "revenant",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 3}]},
    {"word": "banshee",     "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["SHADOW", "UNDEAD", "OFFENSIVE"],
     "actions": [{"action": "Screech", "value": 1}]},

    # --- NAVAL tag family ---
    {"word": "anchor",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NAVAL", "PHYSICAL", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Slow", "value": 1}]},
    {"word": "sail",        "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["NAVAL", "SUPPORT"],
     "actions": [{"action": "Energize", "value": 1}]},
    {"word": "hull",        "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["NAVAL", "DEFENSIVE"],
     "actions": [{"action": "Shield", "value": 2}]},
    {"word": "cannon",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NAVAL", "OFFENSIVE"],
     "actions": [{"action": "Cannonade", "value": 2}]},

    # --- Attune family (save letters for power amplification) ---
    {"word": "harmonize",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "resonate",    "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "synchronize", "target": "Self", "cost": 3, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "calibrate",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "align",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "tune",        "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "chord",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},
    {"word": "frequency",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "SPELL", "SUPPORT"],
     "actions": [{"action": "Attune", "value": 1}]},

    # --- Ignite family (fire damage + burn) ---
    {"word": "kindle",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "inflame",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 2}]},
    {"word": "scald",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "sear",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "char",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "singe",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 1}]},
    {"word": "cauterize",   "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["FIRE", "OFFENSIVE", "RESTORATION", "MEDICAL"],
     "actions": [{"action": "Cauterize", "value": 1}, {"action": "Damage", "value": 2}]},
    {"word": "incinerate",  "target": "SingleEnemy", "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Ignite", "value": 3}]},

    # --- Boil family (burn + water + damage combo) ---
    {"word": "steam",      "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["FIRE", "ELEMENTAL", "OFFENSIVE"],
     "actions": [{"action": "Burn", "value": 1}, {"action": "Water", "value": 2}, {"action": "Damage", "value": 2}]},
    {"word": "geyser",     "target": "AllEnemies",  "cost": 4, "range": 0, "area": "Single",
     "tags": ["FIRE", "ELEMENTAL", "OFFENSIVE", "NATURE"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Water", "value": 3}, {"action": "Damage", "value": 2}]},
    {"word": "simmer",     "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["FIRE", "ELEMENTAL"],
     "actions": [{"action": "Burn", "value": 1}, {"action": "Water", "value": 1}]},
    {"word": "seethe",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["FIRE", "ELEMENTAL", "OFFENSIVE", "DEBUFF"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Water", "value": 2}, {"action": "Damage", "value": 2}]},
    {"word": "blister",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["FIRE", "OFFENSIVE", "DEBUFF"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Damage", "value": 2}]},
    {"word": "stew",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["FIRE", "ELEMENTAL"],
     "actions": [{"action": "Burn", "value": 1}, {"action": "Water", "value": 2}, {"action": "Damage", "value": 1}]},

    # --- Combust family (detonate burning) ---
    {"word": "detonate",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "explode",     "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "erupt",       "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "rupture",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},
    {"word": "burst",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 1}]},
    {"word": "implode",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Combust", "value": 2}]},

    # --- Cauterize family (remove bleeding) ---
    {"word": "tourniquet",  "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["MEDICAL", "SUPPORT", "DEFENSIVE"],
     "actions": [{"action": "Cauterize", "value": 1}, {"action": "Shield", "value": 1}]},
    {"word": "compress",    "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["MEDICAL", "RESTORATION", "SUPPORT"],
     "actions": [{"action": "Cauterize", "value": 1}, {"action": "Heal", "value": 1}]},
    {"word": "staunch",     "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["MEDICAL", "SUPPORT"],
     "actions": [{"action": "Cauterize", "value": 1}]},
    {"word": "suture",      "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["MEDICAL", "RESTORATION"],
     "actions": [{"action": "Cauterize", "value": 1}, {"action": "Heal", "value": 2}]},
    {"word": "styptic",     "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["MEDICAL", "SUPPORT"],
     "actions": [{"action": "Cauterize", "value": 1}]},
    {"word": "clot",        "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["MEDICAL", "NATURE"],
     "actions": [{"action": "Cauterize", "value": 1}]},
    {"word": "coagulate",   "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["MEDICAL", "SUPPORT", "DEFENSIVE"],
     "actions": [{"action": "Cauterize", "value": 1}, {"action": "Shield", "value": 1}]},
    {"word": "brand",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["FIRE", "OFFENSIVE", "MEDICAL"],
     "actions": [{"action": "Cauterize", "value": 1}, {"action": "Burn", "value": 1}, {"action": "Damage", "value": 1}]},
    {"word": "scald",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["FIRE", "OFFENSIVE", "MEDICAL"],
     "actions": [{"action": "Cauterize", "value": 1}, {"action": "Burn", "value": 2}]},

    # --- Visceral family (heavy damage + bleed) ---
    {"word": "gore",        "target": "Melee",       "cost": 1, "range": 0, "area": "Single",
     "tags": ["PHYSICAL", "OFFENSIVE", "MELEE", "DEBUFF"],
     "actions": [{"action": "Damage", "value": 3}, {"action": "Bleed", "value": 1}]},
    {"word": "maul",        "target": "Melee",       "cost": 2, "range": 0, "area": "Single",
     "tags": ["PHYSICAL", "OFFENSIVE", "MELEE", "DEBUFF"],
     "actions": [{"action": "Damage", "value": 4}, {"action": "Bleed", "value": 1}]},
    {"word": "mutilate",    "target": "Melee",       "cost": 2, "range": 0, "area": "Single",
     "tags": ["PHYSICAL", "OFFENSIVE", "MELEE", "DEBUFF"],
     "actions": [{"action": "Damage", "value": 3}, {"action": "Bleed", "value": 3}]},
    {"word": "savage",      "target": "Melee",       "cost": 2, "range": 0, "area": "Single",
     "tags": ["PHYSICAL", "OFFENSIVE", "MELEE", "BEAST"],
     "actions": [{"action": "Damage", "value": 4}, {"action": "Bleed", "value": 2}]},
    {"word": "ravage",      "target": "Melee",       "cost": 2, "range": 0, "area": "Single",
     "tags": ["PHYSICAL", "OFFENSIVE", "MELEE", "DEBUFF"],
     "actions": [{"action": "Damage", "value": 4}, {"action": "Bleed", "value": 2}]},
    {"word": "rend",        "target": "Melee",       "cost": 1, "range": 0, "area": "Single",
     "tags": ["PHYSICAL", "OFFENSIVE", "MELEE", "DEBUFF"],
     "actions": [{"action": "Damage", "value": 3}, {"action": "Bleed", "value": 2}]},
    {"word": "disembowel",  "target": "Melee",       "cost": 3, "range": 0, "area": "Single",
     "tags": ["PHYSICAL", "OFFENSIVE", "MELEE", "DEBUFF"],
     "actions": [{"action": "Damage", "value": 5}, {"action": "Bleed", "value": 3}]},

    # --- Mercenary family (summon recruitable melee fighter) ---
    {"word": "soldier",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["MELEE", "PHYSICAL", "OFFENSIVE", "SOCIAL"],
     "actions": [{"action": "Damage", "value": 2}]},
    {"word": "sellsword",   "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["MELEE", "PHYSICAL", "OFFENSIVE", "SOCIAL"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Plunder", "value": 1}]},
    {"word": "bodyguard",   "target": "Self",        "cost": 2, "range": 0, "area": "Single",
     "tags": ["MELEE", "PHYSICAL", "DEFENSIVE", "SOCIAL"],
     "actions": [{"action": "Shield", "value": 2}]},
    {"word": "gladiator",   "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["MELEE", "PHYSICAL", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 3}]},
    {"word": "bounty",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SOCIAL", "OFFENSIVE"],
     "actions": [{"action": "Plunder", "value": 1}]},
    {"word": "contract",    "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["SOCIAL", "SUPPORT"],
     "actions": [{"action": "BuffStrength", "value": 1}]},
    {"word": "enforcer",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["MELEE", "PHYSICAL", "OFFENSIVE", "SOCIAL"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Stun", "value": 1}]},
    {"word": "warden",      "target": "Self",        "cost": 2, "range": 0, "area": "Single",
     "tags": ["MELEE", "DEFENSIVE", "SOCIAL"],
     "actions": [{"action": "Shield", "value": 2}, {"action": "Hardening", "value": 1}]},
    {"word": "conscript",   "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["MELEE", "PHYSICAL", "SOCIAL"],
     "actions": [{"action": "Damage", "value": 1}]},
    {"word": "knight",      "target": "SingleEnemy", "cost": 3, "range": 0, "area": "Single",
     "tags": ["MELEE", "PHYSICAL", "OFFENSIVE"],
     "actions": [{"action": "Damage", "value": 3}, {"action": "Shield", "value": 1}]},

    # --- Cleave family (physical splash damage, hits primary + one other) ---
    {"word": "axe",           "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 2}]},
    {"word": "hatchet",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 2}]},
    {"word": "cleaver",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 2}]},
    {"word": "scythe",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE", "SHADOW"],
     "actions": [{"action": "Cleave", "value": 3}, {"action": "Bleed", "value": 1}]},
    {"word": "saber",         "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 3}]},
    {"word": "katana",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 3}, {"action": "Bleed", "value": 1}]},
    {"word": "halberd",       "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 3}]},
    {"word": "glaive",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 3}]},
    {"word": "slash",         "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 2}]},
    {"word": "hack",          "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "MELEE", "PHYSICAL", "BLADE"],
     "actions": [{"action": "Cleave", "value": 2}]},

    # --- JUNGLE tag family (tropical/wilderness themed) ---
    {"word": "python",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "BEAST", "JUNGLE", "NATURE"],
     "actions": [{"action": "Damage", "value": 2}, {"action": "Stun", "value": 1}]},
    {"word": "piranha",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "BEAST", "JUNGLE", "NATURE"],
     "actions": [{"action": "Peck", "value": 2}]},
    {"word": "jaguar",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "BEAST", "JUNGLE", "MELEE"],
     "actions": [{"action": "Damage", "value": 3}, {"action": "Bleed", "value": 1}]},
    {"word": "bamboo",        "target": "Self",        "cost": 0, "range": 0, "area": "Single",
     "tags": ["DEFENSIVE", "NATURE", "JUNGLE", "BOTANICAL"],
     "actions": [{"action": "Shield", "value": 1}]},
    {"word": "canopy",        "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["DEFENSIVE", "NATURE", "JUNGLE"],
     "actions": [{"action": "Shield", "value": 2}]},
    {"word": "tropical",      "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["NATURE", "JUNGLE", "RESTORATION"],
     "actions": [{"action": "Heal", "value": 2}]},

    # --- Cataclysm family (massive AoE magic damage, hits all) ---
    {"word": "apocalypse",    "target": "All", "cost": 5, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "ARCANE", "COSMIC", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 5}]},
    {"word": "armageddon",    "target": "All", "cost": 5, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "ARCANE", "FIRE", "COSMIC", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 5}, {"action": "Burn", "value": 2}]},
    {"word": "cataclysm",     "target": "All", "cost": 4, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "ARCANE", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 4}]},
    {"word": "annihilation",  "target": "All", "cost": 5, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "ARCANE", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 5}]},
    {"word": "doomsday",      "target": "All", "cost": 4, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 4}]},
    {"word": "catastrophe",   "target": "All", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 3}]},
    {"word": "devastation",   "target": "All", "cost": 4, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 4}]},
    {"word": "calamity",      "target": "All", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "DESTRUCTION"],
     "actions": [{"action": "Cataclysm", "value": 3}]},

    # --- COSMIC tag family (space/celestial themed) ---
    {"word": "comet",         "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "COSMIC", "ELEMENTAL"],
     "actions": [{"action": "MagicDamage", "value": 3}, {"action": "Burn", "value": 1}]},
    {"word": "meteor",        "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "COSMIC", "ELEMENTAL", "FIRE"],
     "actions": [{"action": "MagicDamage", "value": 3}, {"action": "Burn", "value": 2}]},
    {"word": "asteroid",      "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "COSMIC", "PHYSICAL"],
     "actions": [{"action": "Damage", "value": 3}]},
    {"word": "nebula",        "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ARCANE", "COSMIC", "SUPPORT"],
     "actions": [{"action": "Shield", "value": 2}]},
    {"word": "pulsar",        "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "COSMIC", "ELEMENTAL", "LIGHTNING"],
     "actions": [{"action": "Shock", "value": 3}]},
    {"word": "stellar",       "target": "Self",        "cost": 1, "range": 0, "area": "Single",
     "tags": ["COSMIC", "SUPPORT"],
     "actions": [{"action": "BuffMagicPower", "value": 2}]},

    # --- FIRE tag family (fire-themed words needing FIRE tag) ---
    {"word": "ash",         "target": "SingleEnemy", "cost": 0, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "FIRE"],
     "actions": [{"action": "Burn", "value": 1}]},
    {"word": "cinder",      "target": "SingleEnemy", "cost": 0, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "FIRE"],
     "actions": [{"action": "Burn", "value": 1}]},
    # "pyre" is a seed summon word — do not override here
    {"word": "magma",       "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Melt", "value": 1}]},
    {"word": "lava",        "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE"],
     "actions": [{"action": "Burn", "value": 2}, {"action": "Melt", "value": 1}]},
    {"word": "volcano",     "target": "AllEnemies",  "cost": 4, "range": 0, "area": "Single",
     "tags": ["ELEMENTAL", "OFFENSIVE", "FIRE", "NATURE"],
     "actions": [{"action": "Ignite", "value": 3}, {"action": "Damage", "value": 3}]},

    # --- Sight family (telescope / observation items) ---
    {"word": "spyglass",    "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "binoculars",  "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "lens",        "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "scope",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "monocle",     "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "periscope",   "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "prism",       "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "spectacles",  "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "microscope",  "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},
    {"word": "beacon",      "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "LIGHT", "SIGHT"],
     "actions": [{"action": "Item", "value": 1}]},

    # === Lockpick family ===
    {"word": "skeleton_key", "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "crowbar",      "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "jemmy",        "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "shiv",         "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "probe",        "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "tumbler",      "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "bypass",       "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "latch",        "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "keyhole",      "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},
    {"word": "pin",          "target": "SingleEnemy", "cost": 8, "range": 0, "area": "Single",
     "tags": ["TOOL", "STEALTH"],
     "actions": [{"action": "Lockpick", "value": 1}]},

    # --- Sunder family (strip positive effects + damage) ---
    {"word": "cancel",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF"],
     "actions": [{"action": "Sunder", "value": 1}]},
    {"word": "annul",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF"],
     "actions": [{"action": "Sunder", "value": 1}]},
    {"word": "nullify",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF", "PSYCHIC"],
     "actions": [{"action": "Sunder", "value": 2}]},
    {"word": "dispel",      "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF"],
     "actions": [{"action": "Sunder", "value": 2}]},
    {"word": "rescind",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF"],
     "actions": [{"action": "Sunder", "value": 2}]},
    {"word": "abolish",     "target": "AllEnemies",  "cost": 3, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF", "OFFENSIVE"],
     "actions": [{"action": "Sunder", "value": 1}]},
    {"word": "negate",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF"],
     "actions": [{"action": "Sunder", "value": 2}]},
    {"word": "repeal",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF"],
     "actions": [{"action": "Sunder", "value": 1}]},
    {"word": "invalidate",  "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["NULLIFY", "DEBUFF", "PSYCHIC"],
     "actions": [{"action": "Sunder", "value": 2}, {"action": "Silence", "value": 1}]},
    # --- Silence family (prevent new status effects) ---
    {"word": "mute",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF"],
     "actions": [{"action": "Silence", "value": 2}]},
    {"word": "hush",        "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF"],
     "actions": [{"action": "Silence", "value": 2}]},
    {"word": "gag",         "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF", "PHYSICAL"],
     "actions": [{"action": "Silence", "value": 1}]},
    {"word": "censor",      "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF", "PSYCHIC"],
     "actions": [{"action": "Silence", "value": 3}]},
    {"word": "suppress",    "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF", "PSYCHIC"],
     "actions": [{"action": "Silence", "value": 2}, {"action": "Sunder", "value": 1}]},
    {"word": "muffle",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF"],
     "actions": [{"action": "Silence", "value": 2}]},
    {"word": "squelch",     "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF"],
     "actions": [{"action": "Silence", "value": 2}]},
    {"word": "stifle",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CONTROL", "DEBUFF"],
     "actions": [{"action": "Silence", "value": 1}]},

    # --- Vampiric family (damage enemy + heal self, per-action targeting) ---
    {"word": "leech",       "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["SHADOW", "OFFENSIVE", "RESTORATION"],
     "actions": [
         {"action": "Damage", "value": 2, "target": "SingleEnemy"},
         {"action": "Heal", "value": 1, "target": "Self"}
     ]},
    {"word": "devour",      "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SHADOW", "OFFENSIVE", "BEAST"],
     "actions": [
         {"action": "Damage", "value": 3, "target": "SingleEnemy"},
         {"action": "Heal", "value": 2, "target": "Self"}
     ]},
    {"word": "siphon",      "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SHADOW", "OFFENSIVE", "ARCANE"],
     "actions": [
         {"action": "MagicDamage", "value": 3, "target": "SingleEnemy"},
         {"action": "Heal", "value": 2, "target": "Self"}
     ]},
    {"word": "consume",     "target": "SingleEnemy", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SHADOW", "OFFENSIVE"],
     "actions": [
         {"action": "Damage", "value": 3, "target": "SingleEnemy"},
         {"action": "Heal", "value": 1, "target": "Self"}
     ]},

    # --- Sacrifice family (high damage + self-harm, per-action targeting) ---
    {"word": "immolate",    "target": "SingleEnemy", "cost": 3, "range": 0, "area": "Single",
     "tags": ["FIRE", "OFFENSIVE", "SHADOW"],
     "actions": [
         {"action": "Burn", "value": 3, "target": "SingleEnemy"},
         {"action": "Burn", "value": 1, "target": "Self"}
     ]},
    {"word": "kamikaze",    "target": "AllEnemies", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SHADOW"],
     "actions": [
         {"action": "Damage", "value": 4, "target": "AllEnemies"},
         {"action": "Damage", "value": 3, "target": "Self"}
     ]},
    {"word": "offering",    "target": "AllAllies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["HOLY", "SUPPORT", "SHADOW"],
     "actions": [
         {"action": "Heal", "value": 2, "target": "AllAllies"},
         {"action": "Damage", "value": 2, "target": "Self"}
     ]},
    {"word": "bloodpact",   "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SHADOW", "SUPPORT"],
     "actions": [
         {"action": "BuffStrength", "value": 3, "target": "Self"},
         {"action": "Damage", "value": 2, "target": "Self"}
     ]},

    # --- Rally family (buff allies + debuff enemies, per-action targeting) ---
    {"word": "rally",       "target": "AllAlliesAndSelf", "cost": 3, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [
         {"action": "BuffStrength", "value": 1, "target": "AllAlliesAndSelf"},
         {"action": "Fear", "value": 1, "target": "AllEnemies"}
     ]},
    {"word": "inspire",     "target": "AllAlliesAndSelf", "cost": 2, "range": 0, "area": "Single",
     "tags": ["SUPPORT", "SOCIAL"],
     "actions": [
         {"action": "BuffStrength", "value": 1, "target": "AllAlliesAndSelf"},
         {"action": "Heal", "value": 1, "target": "AllAllies"}
     ]},
    {"word": "intimidate",  "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "SOCIAL", "DEBUFF"],
     "actions": [
         {"action": "Fear", "value": 2, "target": "AllEnemies"},
         {"action": "DebuffStrength", "value": 1, "target": "AllEnemies"}
     ]},

    # --- Flutter family (Scramble + Damage + Attune, AoE disruption) ---
    {"word": "flurry",   "target": "AllEnemies", "cost": 3, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "CONTROL", "AIR"],
     "actions": [
         {"action": "Scramble", "value": 1, "target": "AllEnemies"},
         {"action": "Damage", "value": 2, "target": "AllEnemies"},
         {"action": "Attune", "value": 1, "target": "Self"}
     ]},
    {"word": "whirl",    "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "CONTROL", "AIR"],
     "actions": [
         {"action": "Scramble", "value": 1, "target": "AllEnemies"},
         {"action": "Damage", "value": 1, "target": "AllEnemies"}
     ]},
    {"word": "swirl",    "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "CONTROL", "AIR", "ELEMENTAL"],
     "actions": [
         {"action": "Scramble", "value": 1, "target": "AllEnemies"},
         {"action": "Damage", "value": 1, "target": "AllEnemies"}
     ]},
    {"word": "flit",     "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "AIR"],
     "actions": [
         {"action": "Damage", "value": 1},
         {"action": "Scramble", "value": 1}
     ]},
    {"word": "scatter",  "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "CONTROL", "AIR"],
     "actions": [
         {"action": "Scramble", "value": 1, "target": "AllEnemies"},
         {"action": "Scramble", "value": 1, "target": "AllEnemies"}
     ]},
    {"word": "flicker",  "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "AIR", "LIGHT"],
     "actions": [
         {"action": "Damage", "value": 1},
         {"action": "Scramble", "value": 1}
     ]},
    {"word": "tumble",   "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["OFFENSIVE", "PHYSICAL", "AIR"],
     "actions": [
         {"action": "Damage", "value": 2},
         {"action": "Scramble", "value": 1}
     ]},
    {"word": "breeze",   "target": "AllEnemies", "cost": 1, "range": 0, "area": "Single",
     "tags": ["AIR", "NATURE", "ELEMENTAL"],
     "actions": [
         {"action": "Scramble", "value": 1, "target": "AllEnemies"}
     ]},
    {"word": "zephyr",   "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["AIR", "NATURE", "ELEMENTAL", "SUPPORT"],
     "actions": [
         {"action": "Scramble", "value": 2, "target": "AllEnemies"},
         {"action": "Attune", "value": 1, "target": "Self"}
     ]},
    {"word": "updraft",  "target": "AllEnemies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["AIR", "NATURE", "OFFENSIVE"],
     "actions": [
         {"action": "Scramble", "value": 3, "target": "AllEnemies"},
         {"action": "Damage", "value": 1, "target": "AllEnemies"}
     ]},

    # --- Forge/Craft family (per-action targeting, sacrifice pattern) ---
    {"word": "anvil",       "target": "Self", "cost": 5, "range": 0, "area": "Single",
     "tags": ["CRAFT", "PHYSICAL", "SUPPORT"],
     "actions": [{"action": "Summon", "value": 3}]},
    {"word": "smith",       "target": "AllAllies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["CRAFT", "PHYSICAL", "SUPPORT"],
     "actions": [
         {"action": "BuffStrength", "value": 1, "target": "AllAllies"},
         {"action": "BuffPhysicalDefense", "value": 1, "target": "AllAllies"}
     ]},
    {"word": "temper",      "target": "Self", "cost": 2, "range": 0, "area": "Single",
     "tags": ["CRAFT", "FIRE", "DEFENSIVE"],
     "actions": [
         {"action": "Hardening", "value": 2, "target": "Self"},
         {"action": "Burn", "value": 1, "target": "Self"}
     ]},
    {"word": "weld",        "target": "Self", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CRAFT", "FIRE", "SUPPORT"],
     "actions": [
         {"action": "Shield", "value": 2, "target": "Self"},
         {"action": "Burn", "value": 1, "target": "Self"}
     ]},
    {"word": "hammer",      "target": "SingleEnemy", "cost": 1, "range": 0, "area": "Single",
     "tags": ["CRAFT", "PHYSICAL", "OFFENSIVE", "MELEE"],
     "actions": [{"action": "Smash", "value": 3}]},
    {"word": "bellows",     "target": "AllAllies", "cost": 2, "range": 0, "area": "Single",
     "tags": ["CRAFT", "FIRE", "SUPPORT"],
     "actions": [
         {"action": "BuffStrength", "value": 2, "target": "AllAllies"},
         {"action": "Burn", "value": 1, "target": "Self"}
     ]},
]


def main():
    proc = subprocess.run(
        [sys.executable, BATCH_INSERT, "--draft"],
        input=json.dumps(FAMILIES),
        capture_output=True,
        text=True,
    )
    if proc.stderr:
        print(proc.stderr, end="", file=sys.stderr)
    if proc.returncode != 0:
        print(f"preregister_families failed (exit {proc.returncode})", file=sys.stderr)
        sys.exit(proc.returncode)
    print(f"Pre-registered {len(FAMILIES)} draft words from word families.", file=sys.stderr)


if __name__ == "__main__":
    main()
