// Auto-generated by UnitCodeGenerator — do not edit manually
using UnityEngine;

namespace TextRPG.Core.Encounter
{
    public static class UnitIds
    {
        public static class Enemies
        {
            public const string BAT = "bat";
            public static readonly EntityDefinition BAT_DEF = new(
                Name: "BAT",
                MaxHealth: 30,
                Strength: 4,
                MagicPower: 0,
                PhysicalDefense: 3,
                MagicDefense: 2,
                Luck: 3,
                Color: new Color(0.6f, 0.3f, 0.8f),
                Abilities: new[] { "SCRATCH" });
            public const string GOBLIN = "goblin";
            public static readonly EntityDefinition GOBLIN_DEF = new(
                Name: "GOBLIN",
                MaxHealth: 50,
                Strength: 6,
                MagicPower: 0,
                PhysicalDefense: 4,
                MagicDefense: 2,
                Luck: 2,
                Color: new Color(0.2f, 0.8f, 0.2f),
                Abilities: new[] { "SCRATCH", "HIT" });
            public const string ORC = "orc";
            public static readonly EntityDefinition ORC_DEF = new(
                Name: "ORC",
                MaxHealth: 20,
                Strength: 8,
                MagicPower: 0,
                PhysicalDefense: 4,
                MagicDefense: 2,
                Luck: 1,
                Color: new Color(0f, 1f, 0f),
                Abilities: new[] { "SHOUT", "MACE" });
            public const string SKELETON = "skeleton";
            public static readonly EntityDefinition SKELETON_DEF = new(
                Name: "SKELETON",
                MaxHealth: 50,
                Strength: 8,
                MagicPower: 0,
                PhysicalDefense: 5,
                MagicDefense: 3,
                Luck: 2,
                Color: new Color(0.9f, 0.9f, 0.8f),
                Abilities: new[] { "SLASH", "STRIKE" });
        }

        public static class Summons
        {
        }
    }
}
