// Auto-generates UnitIds.cs from the units + unit_abilities tables in wordactions.db
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using SQLite;
using UnityEditor;
using UnityEngine;

namespace TextRPG.Editor
{
    public static class UnitCodeGenerator
    {
        private const string OutputPath = "Assets/Scripts/Core/Encounter/UnitIds.cs";
        private const string Namespace = "TextRPG.Core.Encounter";

        [Table("units")]
        private class UnitRow
        {
            [Column("unit_id")] public string UnitId { get; set; }
            [Column("display_name")] public string DisplayName { get; set; }
            [Column("unit_type")] public string UnitType { get; set; }
            [Column("max_health")] public int MaxHealth { get; set; }
            [Column("strength")] public int Strength { get; set; }
            [Column("magic_power")] public int MagicPower { get; set; }
            [Column("phys_defense")] public int PhysDefense { get; set; }
            [Column("magic_defense")] public int MagicDefense { get; set; }
            [Column("luck")] public int Luck { get; set; }
            [Column("starting_shield")] public int StartingShield { get; set; }
            [Column("color_r")] public float ColorR { get; set; }
            [Column("color_g")] public float ColorG { get; set; }
            [Column("color_b")] public float ColorB { get; set; }
        }

        [Table("unit_abilities")]
        private class UnitAbilityRow
        {
            [Column("unit_id")] public string UnitId { get; set; }
            [Column("word")] public string Word { get; set; }
        }

        [MenuItem("Tools/TextRPG/Generate Unit IDs")]
        public static void Generate()
        {
            var dbPath = Path.Combine(Application.streamingAssetsPath, "wordactions.db");
            if (!File.Exists(dbPath))
            {
                Debug.LogError($"[UnitCodeGenerator] DB not found at {dbPath}");
                return;
            }

            List<UnitRow> units;
            Dictionary<string, List<string>> abilities;
            using (var db = new SQLiteConnection(dbPath, SQLiteOpenFlags.ReadOnly))
            {
                try
                {
                    units = db.Table<UnitRow>().ToList();
                    var abilityRows = db.Table<UnitAbilityRow>().ToList();
                    abilities = new Dictionary<string, List<string>>();
                    foreach (var row in abilityRows)
                    {
                        if (!abilities.TryGetValue(row.UnitId, out var list))
                        {
                            list = new List<string>();
                            abilities[row.UnitId] = list;
                        }
                        list.Add(row.Word.ToUpperInvariant());
                    }
                }
                catch (SQLiteException e)
                {
                    Debug.LogError($"[UnitCodeGenerator] Failed to read units table: {e.Message}");
                    return;
                }
            }

            if (units.Count == 0)
            {
                Debug.LogWarning("[UnitCodeGenerator] No units found in DB.");
                return;
            }

            var grouped = units.GroupBy(u => u.UnitType).OrderBy(g => g.Key).ToList();
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by UnitCodeGenerator — do not edit manually");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class UnitIds");
            sb.AppendLine("    {");

            foreach (var group in grouped)
            {
                var className = group.Key switch
                {
                    "enemy" => "Enemies",
                    "summon" => "Summons",
                    _ => group.Key.Substring(0, 1).ToUpperInvariant() + group.Key.Substring(1) + "s"
                };

                sb.AppendLine($"        public static class {className}");
                sb.AppendLine("        {");

                foreach (var unit in group.OrderBy(u => u.UnitId))
                {
                    var constName = unit.UnitId.ToUpperInvariant();
                    var abilityList = abilities.TryGetValue(unit.UnitId, out var words)
                        ? string.Join(", ", words.Select(w => $"\"{w}\""))
                        : "";

                    sb.AppendLine($"            public const string {constName} = \"{unit.UnitId}\";");
                    sb.AppendLine($"            public static readonly EnemyDefinition {constName}_DEF = new(");
                    sb.AppendLine($"                Name: \"{unit.DisplayName}\",");
                    sb.AppendLine($"                MaxHealth: {unit.MaxHealth},");
                    sb.AppendLine($"                Strength: {unit.Strength},");
                    sb.AppendLine($"                MagicPower: {unit.MagicPower},");
                    sb.AppendLine($"                PhysicalDefense: {unit.PhysDefense},");
                    sb.AppendLine($"                MagicDefense: {unit.MagicDefense},");
                    sb.AppendLine($"                Luck: {unit.Luck},");
                    sb.AppendLine($"                Color: new Color({unit.ColorR}f, {unit.ColorG}f, {unit.ColorB}f),");
                    sb.AppendLine($"                Abilities: new[] {{ {abilityList} }},");
                    sb.AppendLine($"                StartingShield: {unit.StartingShield});");
                }

                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var fullPath = Path.GetFullPath(OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
            File.WriteAllText(fullPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"[UnitCodeGenerator] Generated {units.Count} units → {OutputPath}");
        }
    }
}
