using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using SQLite;
using UnityEditor;
using UnityEngine;

namespace TextRPG.Editor
{
    public static class WordTagCodeGenerator
    {
        private const string OutputPath = "Assets/Scripts/Core/WordAction/WordTag.cs";
        private const string Namespace = "TextRPG.Core.WordAction";

        [Table("word_tags")]
        private class WordTagRow
        {
            [Column("tag")]
            public string Tag { get; set; }
        }

        [MenuItem("Tools/TextRPG/Generate Word Tags")]
        public static void Generate()
        {
            var dbPath = Path.Combine(Application.streamingAssetsPath, "wordactions.db");
            if (!File.Exists(dbPath))
            {
                Debug.LogError($"[WordTagCodeGenerator] DB not found at {dbPath}");
                return;
            }

            var tags = new HashSet<string>();
            using (var db = new SQLiteConnection(dbPath, SQLiteOpenFlags.ReadOnly))
            {
                try
                {
                    var rows = db.Table<WordTagRow>().ToList();
                    foreach (var row in rows)
                    {
                        var normalized = row.Tag?.Trim().ToUpperInvariant().Replace(' ', '_');
                        if (!string.IsNullOrEmpty(normalized))
                            tags.Add(normalized);
                    }
                }
                catch (SQLiteException e)
                {
                    Debug.LogError($"[WordTagCodeGenerator] Failed to read word_tags table: {e.Message}");
                    return;
                }
            }

            if (tags.Count == 0)
            {
                Debug.LogWarning("[WordTagCodeGenerator] No tags found in DB.");
                return;
            }

            var sorted = tags.OrderBy(t => t).ToList();
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by WordTagCodeGenerator — do not edit manually");
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class WordTag");
            sb.AppendLine("    {");
            foreach (var tag in sorted)
            {
                sb.AppendLine($"        public const string {tag} = \"{tag}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var fullPath = Path.GetFullPath(OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
            File.WriteAllText(fullPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"[WordTagCodeGenerator] Generated {sorted.Count} tags → {OutputPath}");
        }
    }
}
